from .create_professors_by_csv_use_case import CreateProfessorsByCSVUseCase
from .create_professor_use_case import CreateProfessorUseCase
from .get_professors_page_data_use_case import GetProfessorsPageDataUseCase
from .get_professor_details_page_data_use_case import GetProfessorDetailsPageDataUseCase
from .get_subjects_page_data_use_case import GetSubjectsPageDataUseCase
from .create_subject_use_case import CreateSubjectUseCase
from .get_students_page_data_use_case import GetStudentsPageDataUseCase
from .create_student_use_case import CreateStudentUseCase
from .create_students_by_csv_use_case import CreateStudentsByCSVUseCase
from .get_courses_page_data_use_case import GetCoursesPageDataUseCase
from .create_course_use_case import CreateCourseUseCase
from .create_subjects_by_csv_use_case import CreateSubjectsByCSVUseCase
from .create_courses_by_csv_use_case import CreateCoursesByCSVUseCase
from .get_analytics_page_data_use_case import GetAnalyticsPageDataUseCase

get_professor_details_page_data_use_case = GetProfessorDetailsPageDataUseCase()
get_professors_page_data_use_case = GetProfessorsPageDataUseCase()
create_professor_use_case = CreateProfessorUseCase()
create_professors_by_csv_use_case = CreateProfessorsByCSVUseCase()

get_subjects_page_data_use_case = GetSubjectsPageDataUseCase()
create_subject_use_case = CreateSubjectUseCase()
create_subjects_by_csv_use_case = CreateSubjectsByCSVUseCase()

get_students_page_data_use_case = GetStudentsPageDataUseCase()
create_student_use_case = CreateStudentUseCase()
create_students_by_csv_use_case = CreateStudentsByCSVUseCase()

get_courses_page_data_use_case = GetCoursesPageDataUseCase()
create_course_use_case = CreateCourseUseCase()
create_courses_by_csv_use_case = CreateCoursesByCSVUseCase()

get_analytics_page_data_use_case = GetAnalyticsPageDataUseCase()
