version: '3'

services:
  database:
    image: 'joaopetros/unipetros-database:1.0'
    container_name: 'unipetros-database'
    networks:
      - app-tier
    volumes:
      - mysql_data:/bitnami/mysql/data
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: 'joaopetros/unipetros-app:1.0'
    container_name: 'unipetros-app'
    networks:
      - app-tier
    volumes: 
      - .:/home/pn/unipetros
    ports:
      - 5002:5000
    depends_on:
      database:
        condition: service_healthy

networks:
 app-tier:
    driver: bridge

volumes:
 mysql_data:
    driver: local
